name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "5cd8d958399f420fa1f11757a40681d1"				#KV数据库id


